export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SUCCEDED_AUTH_REDIRECT = "SUCCEDED_AUTH_REDIRECT";
export const FAILED_AUTH_REDIRECT = "FAILED_AUTH_REDIRECT";
export const RESET_AUTH_REDIRECT = "RESET_AUTH_REDIRECT";
